import {useEffect,useState} from 'react';
import {useSystem} from '../hooks/useSystem';
import {useAnnouncements} from '../hooks/useAnnouncements';
import {CounterLabel} from '../components/CounterLabel';
import {PublicFooter} from '../components/PublicFooter';
import {MediaPlayer} from '../components/MediaPlayer';
import {Icon} from '../components/Icon';
import type {Multimedia} from '../types';
const fallback:Multimedia={type:'fallback',url:null,playlistId:null,playing:false,muted:false,volume:55};
export function PublicPage(){
 const {state,connected}=useSystem(),{current,audioEnabled,audioError,enableAudio}=useAnnouncements();const [page,setPage]=useState(0),[controls,setControls]=useState(false);
 const turns=state?.turns??[],pages=Math.max(1,Math.ceil(turns.length/5));
 useEffect(()=>{setPage(0);},[turns[0]?.id,turns[0]?.lastAnnouncedAt]);
 useEffect(()=>{if(state?.settings.autoRotate===false||pages<2)return;const id=setInterval(()=>setPage(p=>(p+1)%pages),8000);return()=>clearInterval(id);},[pages,state?.settings.autoRotate]);
 const visible=turns.slice((page%pages)*5,(page%pages)*5+5);
 useEffect(()=>{document.title='Comal++ · Turnos listos';},[]);
 return <div className={`public-screen ${current?'is-announcing':''}`}><section className="public-queue" aria-labelledby="public-title"><header className="public-queue-heading"><div className="title-stroke"/><h1 id="public-title">Turnos listos</h1><p>RETIRA TU PEDIDO EN EL MOSTRADOR</p></header><div className="public-turn-list">{visible.map(turn=><div className="public-turn" key={turn.id}><strong>{turn.number}</strong>{turn.counter!==0&&<CounterLabel counter={turn.counter}/>}</div>)}{!turns.length&&<div className="public-empty"><Icon name="ticket"/><h2>No hay pedidos<br/>listos para recoger</h2><p>Tu número aparecerá aquí.<br/>Mantén tu ticket a la mano.</p></div>}</div>{pages>1&&<div className="public-pagination"><span>{page%pages+1} / {pages}</span>{state?.settings.autoRotate===false&&<button onClick={()=>setPage(p=>(p+1)%pages)} aria-label="Siguiente página de turnos"><Icon name="arrow"/></button>}</div>}</section><section className="public-media" aria-label="Multimedia y anuncios"><MediaPlayer config={state?.multimedia??fallback} playlists={state?.playlists??[]} ducked={Boolean(current)} audioEnabled={audioEnabled}/>{current&&<div className="announcement-backdrop" aria-live="assertive"><div className="announcement-card" key={current.id}><div className="announcement-stroke"/><h2>TURNO LISTO</h2><strong className="announcement-number">{current.number}</strong>{current.counter!==0&&<CounterLabel counter={current.counter}/>}<div className="announcement-rule"/><p>{current.counter?'Por favor acércate al mostrador':'Tu pedido está listo. Acércate a recogerlo.'}</p></div></div>}<div className={`public-tools ${controls?'show':''}`}><button className="public-tool-toggle" onClick={()=>setControls(c=>!c)} aria-label="Opciones de la pantalla"><Icon name="settings"/></button><div className="public-tool-options"><a href="/" className="icon-button" aria-label="Panel del cajero"><Icon name="ticket"/></a><button className="icon-button" onClick={()=>document.documentElement.requestFullscreen?.().catch(()=>{})} aria-label="Pantalla completa"><Icon name="expand"/></button><button className="icon-button" onClick={enableAudio} aria-label="Activar audio"><Icon name="volume"/></button></div></div>{!audioEnabled&&<button className="audio-activation" onClick={enableAudio}><Icon name="volume"/>Activar audio de esta pantalla</button>}{audioError&&<div className="audio-warning" role="alert">{audioError}</div>}{!connected&&<div className="public-connection-warning" role="alert"><Icon name="warning"/>{state?'Sin conexión local. La información puede estar desactualizada. Consulta en caja.':'Conectando con el servidor local…'}</div>}</section><PublicFooter messages={state?.settings.footerMessages??['El café también nos une','Presenta tu ticket al recoger tu pedido']}/></div>;
}
